### ISSUE TITLE
Implement main left menu functions

### ISSUE THREAD

**Issue by serejandmyself** [citizenweb3/validatorinfo#57]
- Can be seen (cemented) though every page
- Whenever a user is on page X it should be highlighted by the menu 
- For sub pages - the highlighted item is the top one. i.e. /validators/citizenweb3 - highlighted will be validators   
- Menu hovers left and back with button click
- Empty pages take or show 404 image and text for now
- Bonus tool: https://github.com/abi/screenshot-to-code =)

**Comment by serejandmyself** [comment]
1) Sometimes the button doesn't work. When i click the arrow to move the menu away, it sometimes, instead of moving the menu to the left, expands the table, but the menu stays "glued" (screenshots attached on tg)

2) After the menu goes away to the left. It should stay there until the person clicks the arrows again. It should not hover back up, as i pass my cursor over it (this can be very annoying, sometimes you scroll the mouse a lot, and you dont want the menu there). Especially that it expands the table.

3) The arrows should be in the correct direction after it slides left. The arrow should change to the right. Then the user knows that he needs to click it, to expand it back (screenshot from figma attached on tg)

**Comment by julmedvedeva** [comment]
- [x] Can be seen (cemented) though every page
- [x] Whenever a user is on page X it should be highlighted by the menu
- [ ] For sub pages - the highlighted item is the top one. i.e. /validators/citizenweb3 - highlighted will be validators
- [x] Menu hovers left and back with button click
- [ ] Empty pages take or show 404 image and text for now
- [x] Sometimes the button doesn't work. When i click the arrow to move the menu away, it sometimes, instead of moving the menu to the left, expands the table, but the menu stays "glued" (screenshots attached on tg)
- [ ] After the menu goes away to the left. It should stay there until the person clicks the arrows again. It should not hover back up, as i pass my cursor over it (this can be very annoying, sometimes you scroll the mouse a lot, and you dont want the menu there). Especially that it expands the table.
- [x] The arrows should be in the correct direction after it slides left. The arrow should change to the right. Then the user knows that he needs to click it, to expand it back (screenshot from figma attached on tg)

**Comment by serejandmyself** [comment]
Implemented on demo visual
